apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-web-app
  name: node-web-app
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8090
  selector:
    app: node-web-app
  type: LoadBalancer
